Be-Secure/BLIman

src/main/bash/bliman-launch-helpers.sh
Called bes list before bes install in launch command.
=> Call bes list before bes install

quick_install.sh, scripts/tmpl/get.bliman.io.tmpl, src/main/bash/bliman-launch-helpers.sh
Made changes in installation scripts according to new design of downloading genesis file manually and editing it before BLIman installation.
=> Updated installation file to use Genesis file.

bliman_setup.sh, src/main/bash/bliman-help.sh, src/main/bash/bliman-main.sh
=> Updated help

src/main/bash/bliman-main.sh
update in help command so that not to execute script further for help command.
=> exit the script if help command is given and help has been displayed

src/main/bash/bliman-init.sh
=> updated init script to read and update the beslighthouse variables

src/main/bash/bliman-init.sh
updated config file for beslighthouse in a
=> updated config file for beslighthouse in a

src/main/bash/bliman-load-genesis.sh, src/main/bash/bliman-main.sh
=> changing exit to return

src/main/bash/bliman-launch-helpers.sh
besman needs version number folder
=> Changes for version number inclusion as required by besman

src/main/bash/bliman-launch-helpers.sh
=> delete tmp directory before installation

src/main/bash/bliman-init.sh
update init file to read the genesis provided variables from stored file.
=> read default location data if BLIMAN_DIR not defined

src/main/bash/bliman-launchlab.sh
renamed BLIMAN_LAB_MODE to BESLAB_LAB_MODE
=> renamed BLIMAN_LAB_MODE to BESLAB_LAB_MODE

README.md
Readme to tell how to test release candidate versions.
=> Update README.md to install and test the release candidate version

README.md
=> replaced with source command

README.md, bliman_setup.sh
=> Replace dot with source

src/main/bash/bliman-attest-OSAR.sh, src/main/bash/bliman-help.sh, src/main/bash/bliman-init.sh, src/main/bash/bliman-main.sh, src/main/bash/bliman-verify-OSAR.sh
=> Added attestation and fix

README.md, bliman_setup.sh, genesis/genesis-AIC.yaml, genesis/genesis-OASP.yaml, genesis/genesis-OSPO.yaml, src/main/bash/bliman-help.sh, src/main/bash/bliman-launchlab.sh, src/main/bash/bliman-load-genesis.sh
Added support for OSPO, OASP and AIC
=> Updated documentation and added support for OASP, OSPO and AIC

bliman_setup.sh, src/main/bash/bliman-attest-OSAR.sh, src/main/bash/bliman-load-genesis.sh, src/main/bash/bliman-verify-OSAR.sh
=> urgent bug fixes

src/main/bash/bliman-launch-AIC.sh, src/main/bash/bliman-launch-OASP.sh, src/main/bash/bliman-launch-OSPO.sh, src/main/bash/bliman-verify-OSAR.sh
=> fixed typos

bliman_setup.sh, src/main/bash/bliman-attest-OSAR.sh
=> some more fixes

bliman_setup.sh, src/main/bash/bliman-load-genesis.sh
=> fixed loading genesis

src/main/bash/bliman-list.sh
Added condition to check if there are installed plugins. If no plugins are installed, appropriate message is displayed
=> Added condition for no installed plugins

src/main/bash/bliman-help.sh, src/main/bash/bliman-info.sh, src/main/bash/bliman-main.sh
=> Fixed #86: Added info command to get the info of plugins

src/main/bash/bliman-help.sh, src/main/bash/bliman-info.sh, src/main/bash/bliman-install.sh, src/main/bash/bliman-main.sh, src/main/bash/bliman-plugin-helpers.sh
=> Fixed #89: Added command to install plugin

src/main/bash/bliman-help.sh, src/main/bash/bliman-main.sh, src/main/bash/bliman-uninstall.sh
=> Fixed #91: Uninstall command for plugins

src/main/bash/bliman-create.sh, src/main/bash/bliman-help.sh, src/main/bash/bliman-info.sh, src/main/bash/bliman-init.sh, src/main/bash/bliman-install.sh, src/main/bash/bliman-main.sh, src/main/bash/bliman-plugin-helpers.sh, src/main/bash/bliman-uninstall.sh, src/main/bash/bliman-validate.sh
=> Fixed #95: Developed create command for plugins

CONTRIBUTING.md, genesis/ADD-UPDATE-GENESIS.md, genesis/contributing.md, src/main/bash/bliman-init.sh
=> updated init and documentation
